### ISSUE TITLE
Nhận xét về đồ án 

### ISSUE THREAD

**Issue by LonggConn** [FinalProject-P4DS/FinalProject-P4DS#7]
Theo những gì mình đọc được thì mình có một số nhận xét về đồ án là:
+Các bạn trình bày theo bố cục của thầy khá tốt
+Các câu hỏi đều không quá dễ để trả lời và có 1 ý nghĩa khi trả lời chúng
Nhưng bên cạnh đó còn một số điểm mình nghĩ cần phải cải thiện như là:
+Số lượng câu hỏi quá nhiều có thể dẫn đến việc nhóm bạn khó mà trình bày được hết trong quỹ thời gian trình bày.
+Dữ liệu thu thập được có khá nhiều giá trị thiếu và dẫn đến khó khăn trong việc khám phá và xử lý có thể dẫn đến những sai sót không đáng có. Nhưng vì đã sử dụng nó rồi nên mình nghĩ điều này chúng ta phải chấp nhận.
+Các bạn sử dụng 1 thư viện ngoài là pyecharts. Đó là 1 thư viện không có trong p4ds-env. Và theo như thầy đã nói để thầy chạy được các bạn nên thêm vào đầu bài làm câu lệnh "!conda install (Thư viện của bạn)" và ghi chú nó để thầy có thể chạy được chứ không nên để nó bên ngoài file readme.

Đó là 1 số điều mình có thể nhận xét sau khi xem qua đồ án của 2 bạn. Hi vọng các bạn có thể dựa vào điều này để hoàn thiện đồ án. Chúc 2 bạn có 1 buổi vấn đáp thật tốt nhé.

**Comment by LonggConn** [comment]
Mình xin lỗi vì mình quên về việc phải để các bạn mở issue :((

**Comment by truongtrieu123** [comment]
Nhóm mình xin lỗi các bạn vì đã mở issue trễ! Xin chân thành cảm ơn những góp ý của các bạn, nhóm mình sẽ khắc phục để hoàn thiện đồ án hơn. Nhóm mình chúc 2 bạn sẽ có  1buổi vấn đáp thật tốt.

**Comment by truongtrieu123** [comment]
Nhóm mình vừa mở một issue mới, rất mong các bạn có thể vào comment lại. Một lần nữa xin lỗi 2 bạn vì sự bất tiện này :((
